[package]
name = "shed"
version = "0.1.0"
authors = ["Rick Richardson <rick.richardson@gmail.com>"]
edition = "2018"


[dependencies]
anyhow = "1.0.40"
bincode = "1.3.2"
dashmap = "4.0.2"
futures = "0.3.13"
pin-project = "1.0.6"
sled = "0.34.6"
tokio = "1.4.0"
